name: IBM_CF Reinstall V2ray

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 12 * * FRI'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        chmod -R 777 ./IBM_Cloud_CLI/
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
        REGION_NUM: ${{ secrets.REGION_NUM }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud login <<EOF
        $IBM_ACCOUNT
        $REGION_NUM
        no
        EOF
    - name: Target IBM Cloud
      env:
        RESOURSE_ID: ${{ secrets.RESOURSE_ID }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud target -g "$RESOURSE_ID"
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf install
    - name: Restart IBM Cloud
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}
        UUID: ${{ secrets.UUID }}
        WS_PATH: ${{ secrets.WS_PATH }}
      run: |
        echo "开始下载v2ray-cloudfoundry文件"
        git submodule update --init --recursive
        cd ./v2ray-cloudfoundry/v2ray
        pwd
        chmod 0755 ./*
        cd ..
        pwd
        cat >  ./manifest.yml  << EOF
        applications:
        - path: .
        name: ${IBM_APP_NAME}
        random-route: true
        memory: 256M
        EOF
        cat >  ./v2ray/config.json  << EOF
        {
            "inbounds": [
                {
                    "port": 8080,
                    "protocol": "vmess",
                    "settings": {
                        "clients": [
                            {
                                "id": "${UUID}",
                                "alterId": 4
                            }
                        ]
                    },
                    "streamSettings": {
                        "network":"ws",
                        "wsSettings": {
                            "path": "${WS_PATH}"
                        }
                    }
                }
            ],
            "outbounds": [
                {
                    "protocol": "freedom",
                    "settings": {}
                }
            ]
        }
        EOF
        pwd
        echo "开始推送配置文件,远程部署!!"
        ../IBM_Cloud_CLI/ibmcloud cf push
        echo "配置完成。"
        
        
